[phases.setup]
aptPkgs = ["python3-dev", "build-essential"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1"